### ISSUE TITLE
Could you provide the Dockerfile used to create the anuragrana/rotating-proxy image?

### ISSUE THREAD

**Issue by PedroRegisPOAR** [anuragrana/scraping_tweets_celery_rabbitmq_docker_cluster#1]
Even in the docker hub it is not provided.

[https://hub.docker.com/r/anuragrana/rotating-proxy]()

**Comment by anuragrana** [comment]
Please refer this article -  https://www.pythoncircle.com/post/518/scraping-10000-tweets-in-60-seconds-using-celery-rabbitmq-and-docker-cluster-with-rotating-proxy/

Link in reference section of article.
